# Generated by Django 5.1.4 on 2024-12-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("last_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("image", models.ImageField(upload_to="coins/")),
            ],
        ),
    ]
