# Generated by Django 5.1.4 on 2024-12-13 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coin",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coin",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
